In [2]:
# Import necessary libraries
import bs4 as bs
import urllib.request 
import pandas as pd
import numpy as np

In [3]:
# 2020 Week 1 Tight End Data
wk_01_source = urllib.request.urlopen("https://stathead.com/tiny/2UILO").read()
soup = bs.BeautifulSoup(wk_01_source, 'lxml')
table = soup.find_all('table')
wk01_20_te = pd.read_html(str(table))[0]
wk01_20_te = wk01_20_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk01_20_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  PHI  Dallas Goedert     1  101   1    16.1
1  DEN       Noah Fant     1   81   1    14.1
2  NOR      Jared Cook     1   80   0     8.0
3  LAC    Hunter Henry     1   73   0     7.3
4  BAL    Mark Andrews     1   58   2    17.8

In [4]:
# 2020 Week 2 Tight End Data
wk_02_source = urllib.request.urlopen("https://stathead.com/tiny/hXXUt").read()
soup = bs.BeautifulSoup(wk_02_source, 'lxml')
table = soup.find_all('table')
wk02_20_te = pd.read_html(str(table))[0]
wk02_20_te = wk02_20_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk02_20_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  MIA    Mike Gesicki     2  130   1    19.0
1  IND     Mo Alie-Cox     2  111   0    11.1
2  LVR   Darren Waller     2  105   1    16.5
3  KAN    Travis Kelce     2   90   1    15.0
4  DAL  Dalton Schultz     2   88   1    12.8

In [5]:
# 2020 Week 3 Tight End Data
wk_03_source = urllib.request.urlopen("https://stathead.com/tiny/1f0l2").read()
soup = bs.BeautifulSoup(wk_03_source, 'lxml')
table = soup.find_all('table')
wk03_20_te = pd.read_html(str(table))[0]
wk03_20_te = wk03_20_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk03_20_te.head()

  Team        Player  Week  Yds  TD  FantPt
0  KAN  Travis Kelce     3   87   0     8.7
1  PHI     Zach Ertz     3   70   0     7.0
2  SEA    Greg Olsen     3   61   0     6.1
3  TEN   Jonnu Smith     3   61   0     6.1
4  CHI  Jimmy Graham     3   60   2    18.0

In [6]:
# 2020 Week 4 Tight End Data
wk_04_source = urllib.request.urlopen("https://stathead.com/tiny/PgZfd").read()
soup = bs.BeautifulSoup(wk_04_source, 'lxml')
table = soup.find_all('table')
wk04_20_te = pd.read_html(str(table))[0]
wk04_20_te = wk04_20_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk04_20_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  SFO   George Kittle     4  183   1    25.1
1  GNB   Robert Tonyan     4   98   3    27.8
2  LVR   Darren Waller     4   88   0     6.8
3  DAL  Dalton Schultz     4   72   1    13.2
4  KAN    Travis Kelce     4   70   0     7.0

In [7]:
# 2020 Week 5 Tight End Data
wk_05_source = urllib.request.urlopen("https://stathead.com/tiny/9wwGi").read()
soup = bs.BeautifulSoup(wk_05_source, 'lxml')
table = soup.find_all('table')
wk05_20_te = pd.read_html(str(table))[0]
wk05_20_te = wk05_20_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk05_20_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  KAN    Travis Kelce     5  108   1    16.8
1  MIA    Mike Gesicki     5   91   0     9.1
2  LAR  Gerald Everett     5   90   0     9.0
3  MIN   Irv Smith Jr.     5   64   0     6.4
4  HOU    Darren Fells     5   57   1    11.7

In [7]:
# 2021 Week 6 Tight End Data
wk_06_source = urllib.request.urlopen("https://stathead.com/tiny/ZZD6o").read()
soup = bs.BeautifulSoup(wk_06_source, 'lxml')
table = soup.find_all('table')
wk06_21_te = pd.read_html(str(table))[0]
wk06_21_te = wk06_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk06_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  MIA    Mike Gesicki     6  115   0    11.5
1  KAN    Travis Kelce     6   99   0     9.9
2  DEN       Noah Fant     6   97   1    15.7
3  DAL  Dalton Schultz     6   79   0     7.9
4  DET  T.J. Hockenson     6   74   0     7.4

In [8]:
# 2021 Week 7 Tight End Data
wk_07_source = urllib.request.urlopen("https://stathead.com/tiny/WCRh2").read()
soup = bs.BeautifulSoup(wk_07_source, 'lxml')
table = soup.find_all('table')
wk07_21_te = pd.read_html(str(table))[0]
wk07_21_te = wk07_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk07_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  ATL      Kyle Pitts     7  163   0    16.3
1  CIN     C.J. Uzomah     7   91   2    21.1
2  MIA    Mike Gesicki     7   85   1    14.5
3  PHI  Dallas Goedert     7   70   0     9.0
4  ARI       Zach Ertz     7   66   1    13.0

In [9]:
# 2021 Week 8 Tight End Data
wk_08_source = urllib.request.urlopen("https://stathead.com/tiny/pquUC").read()
soup = bs.BeautifulSoup(wk_08_source, 'lxml')
table = soup.find_all('table')
wk08_21_te = pd.read_html(str(table))[0]
wk08_21_te = wk08_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk08_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  DET  T.J. Hockenson     8   89   0     8.9
1  PHI  Dallas Goedert     8   72   0     7.2
2  MIN   Tyler Conklin     8   57   0     5.7
3  HOU    Jordan Akins     8   53   0     5.3
4  GNB   Robert Tonyan     8   49   0     4.9

In [12]:
# 2021 Week 9 Tight End Data
wk_09_source = urllib.request.urlopen("https://stathead.com/tiny/NWMIN").read()
soup = bs.BeautifulSoup(wk_09_source, 'lxml')
table = soup.find_all('table')
wk09_21_te = pd.read_html(str(table))[0]
wk09_21_te = wk09_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk09_21_te.head()

  Team         Player  Week  Yds  TD  FantPt
0  SFO  George Kittle     9  101   1    14.1
1  LVR  Darren Waller     9   92   0     9.2
2  CHI      Cole Kmet     9   87   0     8.7
3  KAN   Travis Kelce     9   68   1    12.8
4  ATL     Kyle Pitts     9   62   0     6.2

In [13]:
# 2021 Week 10 Tight End Data
wk_10_source = urllib.request.urlopen("https://stathead.com/tiny/bJXt3").read()
soup = bs.BeautifulSoup(wk_10_source, 'lxml')
table = soup.find_all('table')
wk10_21_te = pd.read_html(str(table))[0]
wk10_21_te = wk10_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk10_21_te.head()

  Team              Player  Week  Yds  TD  FantPt
0  KAN        Travis Kelce    10  119   0    11.9
1  DEN  Albert Okwuegbunam    10   77   0     7.7
2  BAL        Mark Andrews    10   63   1    12.3
3  SEA      Gerald Everett    10   63   0     6.3
4  ATL          Kyle Pitts    10   60   0     6.0

In [14]:
# 2021 Week 11 Tight End Data
wk_11_source = urllib.request.urlopen("https://stathead.com/tiny/7YV7A").read()
soup = bs.BeautifulSoup(wk_11_source, 'lxml')
table = soup.find_all('table')
wk11_21_te = pd.read_html(str(table))[0]
wk11_21_te = wk11_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk11_21_te.head()

  Team         Player  Week  Yds  TD  FantPt
0  LVR  Darren Waller    11  116   0    11.6
1  ARI      Zach Ertz    11   88   2    20.8
2  BUF    Dawson Knox    11   80   0     8.0
3  KAN   Travis Kelce    11   74   0    13.8
4  BAL   Mark Andrews    11   73   0     7.3

In [15]:
# 2021 Week 12 Tight End Data
wk_12_source = urllib.request.urlopen("https://stathead.com/tiny/6jOmr").read()
soup = bs.BeautifulSoup(wk_12_source, 'lxml')
table = soup.find_all('table')
wk12_21_te = pd.read_html(str(table))[0]
wk12_21_te = wk12_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk12_21_te.head()

  Team           Player  Week  Yds  TD  FantPt
0  TAM   Rob Gronkowski    12  123   0    12.3
1  IND       Jack Doyle    12   81   1    14.1
2  BAL     Mark Andrews    12   65   1    12.5
3  CHI        Cole Kmet    12   65   0     6.5
4  CLE  Harrison Bryant    12   50   0     5.0

In [16]:
# 2021 Week 13 Tight End Data
wk_13_source = urllib.request.urlopen("https://stathead.com/tiny/h2eUy").read()
soup = bs.BeautifulSoup(wk_13_source, 'lxml')
table = soup.find_all('table')
wk13_21_te = pd.read_html(str(table))[0]
wk13_21_te = wk13_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk13_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  SFO   George Kittle    13  181   2    30.6
1  PHI  Dallas Goedert    13  105   2    22.5
2  NYG     Evan Engram    13   61   0     6.1
3  TAM  Rob Gronkowski    13   58   2    17.8
4  MIN   Tyler Conklin    13   56   0     5.6

In [17]:
# 2021 Week 14 Tight End Data
wk_14_source = urllib.request.urlopen("https://stathead.com/tiny/ZdAhi").read()
soup = bs.BeautifulSoup(wk_14_source, 'lxml')
table = soup.find_all('table')
wk14_21_te = pd.read_html(str(table))[0]
wk14_21_te = wk14_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk14_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  SFO   George Kittle    14  151   1    21.1
1  BAL    Mark Andrews    14  115   1    17.5
2  NYG    Kyle Rudolph    14   66   0     6.6
3  TAM  Rob Gronkowski    14   62   0     6.2
4  ATL      Kyle Pitts    14   61   0     6.1

In [27]:
# 2021 Week 15 Tight End Data
wk_15_source = urllib.request.urlopen("https://stathead.com/tiny/wWakD").read()
soup = bs.BeautifulSoup(wk_15_source, 'lxml')
table = soup.find_all('table')
wk15_21_te = pd.read_html(str(table))[0]
wk15_21_te = wk15_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk15_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  KAN    Travis Kelce    15  191   2    31.1
1  BAL    Mark Andrews    15  136   2    25.6
2  PHI  Dallas Goedert    15  135   0    13.5
3  SFO   George Kittle    15   93   0     9.3
4  NWE    Hunter Henry    15   77   2    19.7

In [19]:
# 2021 Week 16 Tight End Data
wk_16_source = urllib.request.urlopen("https://stathead.com/tiny/dnW7p").read()
soup = bs.BeautifulSoup(wk_16_source, 'lxml')
table = soup.find_all('table')
wk16_21_te = pd.read_html(str(table))[0]
wk16_21_te = wk16_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk16_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  BAL    Mark Andrews    16  125   1    18.5
1  ATL      Kyle Pitts    16  102   0    10.2
2  DAL  Dalton Schultz    16   82   1    14.2
3  SEA  Gerald Everett    16   68   1    12.8
4  LVR   Foster Moreau    16   67   0     6.7

In [20]:
# 2021 Week 17 Tight End Data
wk_17_source = urllib.request.urlopen("https://stathead.com/tiny/VRoiK").read()
soup = bs.BeautifulSoup(wk_17_source, 'lxml')
table = soup.find_all('table')
wk17_21_te = pd.read_html(str(table))[0]
wk17_21_te = wk17_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk17_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  TAM  Rob Gronkowski    17  115   0    11.5
1  DEN       Noah Fant    17   92   1    15.2
2  BAL    Mark Andrews    17   89   0     8.9
3  PHI  Dallas Goedert    17   71   0     7.1
4  LAR    Tyler Higbee    17   69   0     6.9

In [21]:
# 2021 Week 18 Tight End Data
wk_18_source = urllib.request.urlopen("https://stathead.com/tiny/Pk252").read()
soup = bs.BeautifulSoup(wk_18_source, 'lxml')
table = soup.find_all('table')
wk18_21_te = pd.read_html(str(table))[0]
wk18_21_te = wk18_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk18_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  TAM  Rob Gronkowski    18  137   0    13.7
1  NWE    Hunter Henry    18   86   0     8.6
2  BAL    Mark Andrews    18   85   0     8.5
3  ARI       Zach Ertz    18   84   0     8.4
4  LAC      Jared Cook    18   80   0     8.0

In [22]:
season_2021 = pd.concat(
    [wk01_21_te, wk02_21_te, wk03_21_te, wk04_21_te, wk05_21_te, wk06_21_te,wk07_21_te, wk08_21_te, wk09_21_te, wk10_21_te,
    wk11_21_te, wk12_21_te, wk13_21_te, wk14_21_te, wk15_21_te, wk16_21_te, wk17_21_te, wk18_21_te], axis=0)

display(season_2021.head(75))
display(season_2021.tail(75))

   Team               Player  Week  Yds  TD  FantPt
0   LVR        Darren Waller     1  105   1    16.5
1   DET       T.J. Hockenson     1   97   1    17.7
2   TAM       Rob Gronkowski     1   90   2    21.0
3   SFO        George Kittle     1   78   0     7.8
4   KAN         Travis Kelce     1   76   2    19.6
..  ...                  ...   ...  ...  ..     ...
23  JAX  James O'Shaughnessy     2   24   0     2.4
24  DEN   Albert Okwuegbunam     2   24   0     2.4
25  NYG          Kaden Smith     2   24   0     2.4
26  TAM          O.J. Howard     2   21   0     2.1
27  KAN           Blake Bell     2   20   0     2.0

[75 rows x 6 columns]

   Team         Player  Week  Yds  TD  FantPt
19  IND    Mo Alie-Cox    17   28   0     2.8
20  CLE  Austin Hooper    17   28   0     2.8
21  CLE    David Njoku    17   28   1     8.8
22  KAN   Travis Kelce    17   25   1     8.4
23  CHI      Cole Kmet    17   25   0     2.5
..  ...            ...   ...  ...  ..     ...
43  WAS     John Bates    18    5   0     0.5
44  NYJ    Tyler Kroft    18    5   0     0.5
45  NYG    Evan Engram    18    4   0     0.4
46  TEN    Geoff Swaim    18    2   0     0.2
47  BAL    Josh Oliver    18    1   0     0.1

[75 rows x 6 columns]

In [25]:
# Add collumn to dataframe to establish point threshold of postion
# for Tight End we want to have a touchdown and 10 yards that equals 7 points
season_2021["Threshold"] = np.where(season_2021["FantPt"] >= 7, 1, 0)

season_2021.head(75)

   Team               Player  Week  Yds  TD  FantPt  Threshold
0   LVR        Darren Waller     1  105   1    16.5          1
1   DET       T.J. Hockenson     1   97   1    17.7          1
2   TAM       Rob Gronkowski     1   90   2    21.0          1
3   SFO        George Kittle     1   78   0     7.8          1
4   KAN         Travis Kelce     1   76   2    19.6          1
..  ...                  ...   ...  ...  ..     ...        ...
23  JAX  James O'Shaughnessy     2   24   0     2.4          0
24  DEN   Albert Okwuegbunam     2   24   0     2.4          0
25  NYG          Kaden Smith     2   24   0     2.4          0
26  TAM          O.J. Howard     2   21   0     2.1          0
27  KAN           Blake Bell     2   20   0     2.0          0

[75 rows x 7 columns]

In [26]:
# Understand spread
season_2021['Threshold'].value_counts()

0    684
1    197
Name: Threshold, dtype: int64

In [ ]:
# rows = soup.find_all('tr', class_= lambda table_rows: table_rows != "thead")
# player_stats =[[td.getText() for td in rows[i].find_all ('td')]
               # for i in range(len(rows))]
# player_stats = player_stats[2:]

# print(player_stats)

In [ ]:
mergeDf = wk01_21_te.merge(wk02_21_te, on='Player')

In [ ]:
mergeDf.head()

In [ ]:
 source = urllib.request.urlopen("https://stathead.com/tiny/zNzPx").read()
 soup = bs.BeautifulSoup(source, 'lxml')
table = soup.find_all('table')
wk03_21_te = pd.read_html(str(table))[0]
wk03_21_te = wk03_21_te[['Player', 'Week', 'FantPt']].copy()
wk03_21_te.head()

In [ ]:
frames = [wk01_21_te, wk02_21_te, wk03_21_te]
result = pd.concat(frames)
display(result.head(50))
display(result.tail(50))