In [2]:
import bs4 as bs
import urllib.request 
import pandas as pd
import numpy as np

In [50]:
wk_01_source = urllib.request.urlopen("https://stathead.com/tiny/ckc9q").read()
soup = bs.BeautifulSoup(wk_01_source, 'lxml')
table = soup.find_all('table')
wk01_21_te = pd.read_html(str(table))[0]
wk01_21_te = wk01_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk01_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  LVR   Darren Waller     1  105   1    16.5
1  DET  T.J. Hockenson     1   97   1    17.7
2  TAM  Rob Gronkowski     1   90   2    21.0
3  SFO   George Kittle     1   78   0     7.8
4  KAN    Travis Kelce     1   76   2    19.6

In [42]:
wk_02_source = urllib.request.urlopen("https://stathead.com/tiny/j81UQ").read()
soup = bs.BeautifulSoup(wk_02_source, 'lxml')
table = soup.find_all('table')
wk02_21_te = pd.read_html(str(table))[0]
wk02_21_te = wk02_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk02_21_te.head()

           Player  Week  FantPt
0    Travis Kelce     2    16.9
1   Maxx Williams     2     9.4
2      Kyle Pitts     2     7.3
3  T.J. Hockenson     2    12.6
4   Darren Waller     2     6.5

In [43]:
wk_03_source = urllib.request.urlopen("https://stathead.com/tiny/zNzPx").read()
soup = bs.BeautifulSoup(wk_03_source, 'lxml')
table = soup.find_all('table')
wk03_21_te = pd.read_html(str(table))[0]
wk03_21_te = wk03_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk03_21_te.head()

           Player  Week  FantPt
0    Mark Andrews     3    10.9
1    Travis Kelce     3    10.4
2   George Kittle     3    10.1
3    Mike Gesicki     3     8.6
4  Dalton Schultz     3    20.0

In [46]:
wk_04_source = urllib.request.urlopen("https://stathead.com/tiny/SmW69").read()
soup = bs.BeautifulSoup(wk_04_source, 'lxml')
table = soup.find_all('table')
wk04_21_te = pd.read_html(str(table))[0]
wk04_21_te = wk04_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk04_21_te.head()

          Player  Week  FantPt
0    C.J. Uzomah     4    21.5
1     Jared Cook     4    13.0
2   Mark Andrews     4     6.7
3  Maxx Williams     4    12.6
4      Zach Ertz     4     6.0

In [48]:
wk_05_source = urllib.request.urlopen("https://stathead.com/tiny/goRXc").read()
soup = bs.BeautifulSoup(wk_05_source, 'lxml')
table = soup.find_all('table')
wk05_21_te = pd.read_html(str(table))[0]
wk05_21_te = wk05_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk05_21_te.head()

           Player  Week  FantPt
0     David Njoku     5    20.9
1    Mark Andrews     5    30.7
2      Kyle Pitts     5    17.9
3     Dawson Knox     5    17.7
4  Dalton Schultz     5     7.9

In [51]:
wk_06_source = urllib.request.urlopen("https://stathead.com/tiny/ZZD6o").read()
soup = bs.BeautifulSoup(wk_06_source, 'lxml')
table = soup.find_all('table')
wk06_21_te = pd.read_html(str(table))[0]
wk06_21_te = wk06_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk06_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  MIA    Mike Gesicki     6  115   0    11.5
1  KAN    Travis Kelce     6   99   0     9.9
2  DEN       Noah Fant     6   97   1    15.7
3  DAL  Dalton Schultz     6   79   0     7.9
4  DET  T.J. Hockenson     6   74   0     7.4

In [54]:
wk_07_source = urllib.request.urlopen("https://stathead.com/tiny/WCRh2").read()
soup = bs.BeautifulSoup(wk_07_source, 'lxml')
table = soup.find_all('table')
wk07_21_te = pd.read_html(str(table))[0]
wk07_21_te = wk07_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk07_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  ATL      Kyle Pitts     7  163   0    16.3
1  CIN     C.J. Uzomah     7   91   2    21.1
2  MIA    Mike Gesicki     7   85   1    14.5
3  PHI  Dallas Goedert     7   70   0     9.0
4  ARI       Zach Ertz     7   66   1    13.0

In [55]:
wk_08_source = urllib.request.urlopen("https://stathead.com/tiny/pquUC").read()
soup = bs.BeautifulSoup(wk_08_source, 'lxml')
table = soup.find_all('table')
wk08_21_te = pd.read_html(str(table))[0]
wk08_21_te = wk08_21_te[['Team', 'Player', 'Week', 'Yds', 'TD', 'FantPt']].copy()
wk08_21_te.head()

  Team          Player  Week  Yds  TD  FantPt
0  DET  T.J. Hockenson     8   89   0     8.9
1  PHI  Dallas Goedert     8   72   0     7.2
2  MIN   Tyler Conklin     8   57   0     5.7
3  HOU    Jordan Akins     8   53   0     5.3
4  GNB   Robert Tonyan     8   49   0     4.9

In [16]:
# rows = soup.find_all('tr', class_= lambda table_rows: table_rows != "thead")
# player_stats =[[td.getText() for td in rows[i].find_all ('td')]
               # for i in range(len(rows))]
# player_stats = player_stats[2:]

# print(player_stats)

In [30]:
mergeDf = wk01_21_te.merge(wk02_21_te, on='Player')

In [35]:
mergeDf.head()

           Player  Week_x  FantPt_x  Week_y  FantPt_y
0   Darren Waller       1      16.5       2       6.5
1  T.J. Hockenson       1      17.7       2      12.6
2  Rob Gronkowski       1      21.0       2      15.9
3   George Kittle       1       7.8       2       1.7
4    Travis Kelce       1      19.6       2      16.9

In [36]:
 source = urllib.request.urlopen("https://stathead.com/tiny/zNzPx").read()
 soup = bs.BeautifulSoup(source, 'lxml')
table = soup.find_all('table')
wk03_21_te = pd.read_html(str(table))[0]
wk03_21_te = wk03_21_te[['Player', 'Week', 'FantPt']].copy()
wk03_21_te.head()

           Player  Week  FantPt
0    Mark Andrews     3    10.9
1    Travis Kelce     3    10.4
2   George Kittle     3    10.1
3    Mike Gesicki     3     8.6
4  Dalton Schultz     3    20.0

In [40]:
frames = [wk01_21_te, wk02_21_te, wk03_21_te]
result = pd.concat(frames)
display(result.head(50))
display(result.tail(50))

                 Player  Week  FantPt
0         Darren Waller     1    16.5
1        T.J. Hockenson     1    17.7
2        Rob Gronkowski     1    21.0
3         George Kittle     1     7.8
4          Travis Kelce     1    19.6
5           David Njoku     1     7.6
6          Tyler Higbee     1     6.8
7         Pharaoh Brown     1     6.7
8             Noah Fant     1     6.2
9            Jared Cook     1     5.6
10  James O'Shaughnessy     1     4.8
11       Dalton Schultz     1     4.5
12       Dallas Goedert     1    10.2
13            Cole Kmet     1     4.2
14          Jonnu Smith     1     4.8
15        Tyler Conklin     1     4.1
16          Dawson Knox     1     4.1
17          Will Dissly     1     3.7
18          C.J. Uzomah     1     3.5
19            Zach Ertz     1     3.4
20         Hunter Henry     1     3.1
21           Kyle Pitts     1     3.1
22         Logan Thomas     1     9.0
23         Hayden Hurst     1     2.8
24        Austin Hooper     1     2.7
25          Tyler Kroft     1     2.6
26       Pat Freiermuth     1     2.4
27         Ryan Griffin     1     2.2
28       Chris Manhertz     1     8.2
29           Jack Doyle     1     2.1
30         Mark Andrews     1     2.0
31       Gerald Everett     1     8.0
32         Blake Jarwin     1     2.0
33           Eric Ebron     1     1.9
34       Marcedes Lewis     1     1.9
35        Adam Trautman     1     1.8
36      Harrison Bryant     1     1.7
37           Ian Thomas     1     1.7
38   Albert Okwuegbunam     1     5.6
39         Jimmy Graham     1     1.1
40        Durham Smythe     1     0.9
41         Kyle Rudolph     1     0.8
42        Robert Tonyan     1     0.8
43         Eric Saubert     1     0.7
44           Blake Bell     1     0.5
45         Darren Fells     1     0.2
46     Stephen Anderson     1     0.1
0          Travis Kelce     2    16.9
1         Maxx Williams     2     9.4
2            Kyle Pitts     2     7.3

                Player  Week  FantPt
1         Travis Kelce     3    10.4
2        George Kittle     3    10.1
3         Mike Gesicki     3     8.6
4       Dalton Schultz     3    20.0
5        Tyler Conklin     3    13.0
6       Dallas Goedert     3     6.6
7       Rob Gronkowski     3     5.5
8       Gerald Everett     3     5.4
9        Darren Waller     3     5.4
10           Zach Ertz     3    11.3
11         Dawson Knox     3    10.9
12        Logan Thomas     3     8.2
13        Tyler Higbee     3    10.0
14         Will Dissly     3     3.9
15        Hunter Henry     3     3.6
16       Cameron Brate     3     3.5
17        Darren Fells     3     3.5
18          Kyle Pitts     3     3.5
19        Jordan Akins     3     3.2
20       Tommy Tremble     3     9.7
21          Jared Cook     3     2.7
22         Geoff Swaim     3     2.7
23      Pat Freiermuth     3     8.2
24         Evan Engram     3     0.1
25       Austin Hooper     3     7.9
26       Donald Parham     3     1.9
27       Maxx Williams     3     1.9
28           Noah Fant     3     1.5
29     Jacob Hollister     3     1.5
30         Mo Alie-Cox     3     1.4
31        Blake Jarwin     3     1.4
32         Tyler Kroft     3     1.2
33         O.J. Howard     3     1.1
34           Cole Kmet     3     1.1
35          Jack Doyle     3     1.0
36      T.J. Hockenson     3     1.0
37         Kaden Smith     3     0.9
38       Foster Moreau     3     0.8
39       MyCole Pruitt     3     0.7
40           Lee Smith     3     6.7
41          Blake Bell     3     0.6
42  Albert Okwuegbunam     3     0.6
43         Josh Oliver     3     0.6
44       Robert Tonyan     3     0.6
45           Noah Gray     3     0.5
46        Ryan Griffin     3     0.5
47      Josiah Deguara     3     0.4
48         Jonnu Smith     3     0.4
49        Tommy Hudson     3     0.3
50       Tommy Sweeney     3     0.2